# Generated by Django 3.2.14 on 2022-08-02 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='skill',
            field=models.CharField(choices=[('Quick-and-easy', 'Quick-and-easy'), ('A-bit-Flashy', 'A-bit-Flashy'), ('Challenge-me', 'Challenge-me')], default='Quick-and-easy', max_length=15),
        ),
    ]
