# Generated by Django 3.2.14 on 2022-08-25 18:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipe', '0004_auto_20220820_2041'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='likes',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cheers',
            field=models.ManyToManyField(blank=True, related_name='recipe_cheers', to=settings.AUTH_USER_MODEL),
        ),
    ]
