# Generated by Django 3.2.14 on 2022-08-28 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20220825_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='notes',
        ),
    ]
